INSERT INTO BOOK (BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES) VALUES('History of Amazon Valley','Ross Suarez','0','2');
INSERT INTO BOOK (BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES) VALUES('Language Fundamentals','H S parkmay','5','5');
INSERT INTO BOOK (BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES) VALUES('Learning Spark','Databricks','1','3');